# Welcome to Jekyll!
#

# Site settings
title: Vishwajeet
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: Vishwajeet Bhagyawant # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "portfolio" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  github: https://github.com/vishwajeetiitb
  linkedin-square: https://linkedin.com/in/vishwajeet-bhagyawant-132650192
  facebook-official: https://www.facebook.com/vishwajeet.bhagyawant.9
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/vishwajeetbhagyawant/
  #youtube-square:
  #spotify:
  # stack-overflow: https://github.com/vishwajeetiitb
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  # linux: 
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

#Index 
intro_line: Hello this is Vishwajeet
intro_description: I AM MECHATRONICS ENTHUSIAST AND DEDICATED TO ROBOTICS. DOING ROBOTICS STUFF GIVES ME JOY
